version: '2'

services:

  zephyrjs-ide:
    build:
      context: .
      dockerfile: ./.docker/angular-seed.development.dockerfile
    command: npm start
    container_name: zephyrjs-ide-start
    image: zephyrjs-ide
    networks:
      - dev-network
    ports:
      - '8000:8000'

networks:
  dev-network:
    driver: bridge
