version: '2'

services:

  dist-build:
    container_name: dist-build
    image: dist-build
    build:
      context: .
      dockerfile: ./.docker/dist-build.production.dockerfile
    ports:
      - '8000:8000'
